## Problem Statement

Q.1 Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
def divide():
    return 5/0
try:
    divide()
except ZeroDivisionError as ze:
    print("dividing by zero error")
except:
    print("other exception")

dividing by zero error


Q.2 Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

    Hint: Subject,Verb and Object should be declared in the program as shown below.
    subjects=["Americans ","Indians"]
    verbs=["play","watch"]
    objects=["Baseball","Cricket"]

    Output should come as below:
    Americans play Baseball.
    Americans play Cricket.
    Americans watch Baseball.
    Americans watch Cricket.
    Indians play Baseball.
    Indians play Cricket.
    Indians watch Baseball.
    Indians watch Cricket.

In [4]:
subjects=["Americans","Indians"]
verbs=["Play","Watch"]
objects=["Baseball","Cricket"]
sentance=[(sub+" "+verb+" "+obj) for sub in subjects for verb in verbs for obj in objects]
for sen in sentance:
    print(sen)

Americans Play Baseball
Americans Play Cricket
Americans Watch Baseball
Americans Watch Cricket
Indians Play Baseball
Indians Play Cricket
Indians Watch Baseball
Indians Watch Cricket


Q.3 Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

    HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.

In [10]:
import numpy as np
def gen_vender_matrix(ipvector,n,increasing=False):
    if not increasing:
        opt_mat=np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        opt_mat=np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    return opt_mat
print("----Output----")

inputvector=np.array([1,2,3,4,5])
no_col_optmat=3
op_mat_dec_order=gen_vender_matrix(inputvector,no_col_optmat,False)
op_mat_inc_order=gen_vender_matrix(inputvector,no_col_optmat,True)

print("Input vector",inputvector,"\n")
print("Number of columns in output matrix should be ",no_col_optmat,"\n")
print("Vandar matrix of the input array descring order ",op_mat_dec_order,"\n")
print("Vandar matrix of the input array incresing order ",op_mat_inc_order,"\n")

inputvector=np.array([1,2,4,6,8,10])
no_col_optmat=5
op_mat_dec_order=gen_vender_matrix(inputvector,no_col_optmat,False)
op_mat_inc_order=gen_vender_matrix(inputvector,no_col_optmat,True)

print("Input vector",inputvector,"\n")
print("Number of columns in output matrix should be ",no_col_optmat,"\n")
print("Vandar matrix of the input array descring order ",op_mat_dec_order,"\n")
print("Vandar matrix of the input array incresing order ",op_mat_inc_order,"\n")


----Output----
Input vector [1 2 3 4 5] 

Number of columns in output matrix should be  3 

Vandar matrix of the input array descring order  [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Vandar matrix of the input array incresing order  [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 

Input vector [ 1  2  4  6  8 10] 

Number of columns in output matrix should be  5 

Vandar matrix of the input array descring order  [[    1     1     1     1     1]
 [   16     8     4     2     1]
 [  256    64    16     4     1]
 [ 1296   216    36     6     1]
 [ 4096   512    64     8     1]
 [10000  1000   100    10     1]] 

Vandar matrix of the input array incresing order  [[    1     1     1     1     1]
 [    1     2     4     8    16]
 [    1     4    16    64   256]
 [    1     6    36   216  1296]
 [    1     8    64   512  4096]
 [    1    10   100  1000 10000]] 

